### ISSUE TITLE
T1_1 Create a Sign In Page

### ISSUE THREAD

**Issue by RalphsGit** [habib-jarweh/ECSE428-PROJECT#11]
Create a sign-in page for users to authenticate their access to the platform.

Requirements:

Design a user-friendly sign-in interface.
Implement validation for username and password fields.
Include error handling for incorrect credentials.
Ensure compatibility across different devices and browsers.
Maintain consistency with the platform's visual style and branding.
Integrate with existing authentication systems if applicable.
Write clear and concise code with comments for future reference.

**Comment by clarajabbour** [comment]
Pushed this page, waiting for review to see if final page
